//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: descriptor.proto
namespace google.protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FileDescriptorSet")]
  public partial class FileDescriptorSet : global::ProtoBuf.IExtensible
  {
    public FileDescriptorSet() {}
    
    private readonly global::System.Collections.Generic.List<google.protobuf.FileDescriptorProto> _file = new global::System.Collections.Generic.List<google.protobuf.FileDescriptorProto>();
    [global::ProtoBuf.ProtoMember(1, Name=@"file", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<google.protobuf.FileDescriptorProto> file
    {
      get { return _file; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FileDescriptorProto")]
  public partial class FileDescriptorProto : global::ProtoBuf.IExtensible
  {
    public FileDescriptorProto() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name?? ""; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return this._name != null; }
      set { if (value == (this._name== null)) this._name = value ? this.name : (string)null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    
    private string _package;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"package", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string package
    {
      get { return _package?? ""; }
      set { _package = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool packageSpecified
    {
      get { return this._package != null; }
      set { if (value == (this._package== null)) this._package = value ? this.package : (string)null; }
    }
    private bool ShouldSerializepackage() { return packageSpecified; }
    private void Resetpackage() { packageSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<string> _dependency = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"dependency", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> dependency
    {
      get { return _dependency; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _public_dependency = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(10, Name=@"public_dependency", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> public_dependency
    {
      get { return _public_dependency; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _weak_dependency = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(11, Name=@"weak_dependency", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> weak_dependency
    {
      get { return _weak_dependency; }
    }
  
    private readonly global::System.Collections.Generic.List<google.protobuf.DescriptorProto> _message_type = new global::System.Collections.Generic.List<google.protobuf.DescriptorProto>();
    [global::ProtoBuf.ProtoMember(4, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<google.protobuf.DescriptorProto> message_type
    {
      get { return _message_type; }
    }
  
    private readonly global::System.Collections.Generic.List<google.protobuf.EnumDescriptorProto> _enum_type = new global::System.Collections.Generic.List<google.protobuf.EnumDescriptorProto>();
    [global::ProtoBuf.ProtoMember(5, Name=@"enum_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<google.protobuf.EnumDescriptorProto> enum_type
    {
      get { return _enum_type; }
    }
  
    private readonly global::System.Collections.Generic.List<google.protobuf.ServiceDescriptorProto> _service = new global::System.Collections.Generic.List<google.protobuf.ServiceDescriptorProto>();
    [global::ProtoBuf.ProtoMember(6, Name=@"service", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<google.protobuf.ServiceDescriptorProto> service
    {
      get { return _service; }
    }
  
    private readonly global::System.Collections.Generic.List<google.protobuf.FieldDescriptorProto> _extension = new global::System.Collections.Generic.List<google.protobuf.FieldDescriptorProto>();
    [global::ProtoBuf.ProtoMember(7, Name=@"extension", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<google.protobuf.FieldDescriptorProto> extension
    {
      get { return _extension; }
    }
  
    private google.protobuf.FileOptions _options = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"options", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public google.protobuf.FileOptions options
    {
      get { return _options; }
      set { _options = value; }
    }
    private google.protobuf.SourceCodeInfo _source_code_info = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"source_code_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public google.protobuf.SourceCodeInfo source_code_info
    {
      get { return _source_code_info; }
      set { _source_code_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DescriptorProto")]
  public partial class DescriptorProto : global::ProtoBuf.IExtensible
  {
    public DescriptorProto() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name?? ""; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return this._name != null; }
      set { if (value == (this._name== null)) this._name = value ? this.name : (string)null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<google.protobuf.FieldDescriptorProto> _field = new global::System.Collections.Generic.List<google.protobuf.FieldDescriptorProto>();
    [global::ProtoBuf.ProtoMember(2, Name=@"field", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<google.protobuf.FieldDescriptorProto> field
    {
      get { return _field; }
    }
  
    private readonly global::System.Collections.Generic.List<google.protobuf.FieldDescriptorProto> _extension = new global::System.Collections.Generic.List<google.protobuf.FieldDescriptorProto>();
    [global::ProtoBuf.ProtoMember(6, Name=@"extension", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<google.protobuf.FieldDescriptorProto> extension
    {
      get { return _extension; }
    }
  
    private readonly global::System.Collections.Generic.List<google.protobuf.DescriptorProto> _nested_type = new global::System.Collections.Generic.List<google.protobuf.DescriptorProto>();
    [global::ProtoBuf.ProtoMember(3, Name=@"nested_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<google.protobuf.DescriptorProto> nested_type
    {
      get { return _nested_type; }
    }
  
    private readonly global::System.Collections.Generic.List<google.protobuf.EnumDescriptorProto> _enum_type = new global::System.Collections.Generic.List<google.protobuf.EnumDescriptorProto>();
    [global::ProtoBuf.ProtoMember(4, Name=@"enum_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<google.protobuf.EnumDescriptorProto> enum_type
    {
      get { return _enum_type; }
    }
  
    private readonly global::System.Collections.Generic.List<google.protobuf.DescriptorProto.ExtensionRange> _extension_range = new global::System.Collections.Generic.List<google.protobuf.DescriptorProto.ExtensionRange>();
    [global::ProtoBuf.ProtoMember(5, Name=@"extension_range", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<google.protobuf.DescriptorProto.ExtensionRange> extension_range
    {
      get { return _extension_range; }
    }
  
    private readonly global::System.Collections.Generic.List<google.protobuf.OneofDescriptorProto> _oneof_decl = new global::System.Collections.Generic.List<google.protobuf.OneofDescriptorProto>();
    [global::ProtoBuf.ProtoMember(8, Name=@"oneof_decl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<google.protobuf.OneofDescriptorProto> oneof_decl
    {
      get { return _oneof_decl; }
    }
  
    private google.protobuf.MessageOptions _options = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"options", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public google.protobuf.MessageOptions options
    {
      get { return _options; }
      set { _options = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExtensionRange")]
  public partial class ExtensionRange : global::ProtoBuf.IExtensible
  {
    public ExtensionRange() {}
    
    private int? _start;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"start", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int start
    {
      get { return _start?? default(int); }
      set { _start = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool startSpecified
    {
      get { return this._start != null; }
      set { if (value == (this._start== null)) this._start = value ? this.start : (int?)null; }
    }
    private bool ShouldSerializestart() { return startSpecified; }
    private void Resetstart() { startSpecified = false; }
    
    private int? _end;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"end", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int end
    {
      get { return _end?? default(int); }
      set { _end = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool endSpecified
    {
      get { return this._end != null; }
      set { if (value == (this._end== null)) this._end = value ? this.end : (int?)null; }
    }
    private bool ShouldSerializeend() { return endSpecified; }
    private void Resetend() { endSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FieldDescriptorProto")]
  public partial class FieldDescriptorProto : global::ProtoBuf.IExtensible
  {
    public FieldDescriptorProto() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name?? ""; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return this._name != null; }
      set { if (value == (this._name== null)) this._name = value ? this.name : (string)null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    
    private int? _number;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int number
    {
      get { return _number?? default(int); }
      set { _number = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool numberSpecified
    {
      get { return this._number != null; }
      set { if (value == (this._number== null)) this._number = value ? this.number : (int?)null; }
    }
    private bool ShouldSerializenumber() { return numberSpecified; }
    private void Resetnumber() { numberSpecified = false; }
    
    private google.protobuf.FieldDescriptorProto.Label? _label;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"label", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public google.protobuf.FieldDescriptorProto.Label label
    {
      get { return _label?? google.protobuf.FieldDescriptorProto.Label.LABEL_OPTIONAL; }
      set { _label = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool labelSpecified
    {
      get { return this._label != null; }
      set { if (value == (this._label== null)) this._label = value ? this.label : (google.protobuf.FieldDescriptorProto.Label?)null; }
    }
    private bool ShouldSerializelabel() { return labelSpecified; }
    private void Resetlabel() { labelSpecified = false; }
    
    private google.protobuf.FieldDescriptorProto.Type? _type;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public google.protobuf.FieldDescriptorProto.Type type
    {
      get { return _type?? google.protobuf.FieldDescriptorProto.Type.TYPE_DOUBLE; }
      set { _type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool typeSpecified
    {
      get { return this._type != null; }
      set { if (value == (this._type== null)) this._type = value ? this.type : (google.protobuf.FieldDescriptorProto.Type?)null; }
    }
    private bool ShouldSerializetype() { return typeSpecified; }
    private void Resettype() { typeSpecified = false; }
    
    private string _type_name;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"type_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string type_name
    {
      get { return _type_name?? ""; }
      set { _type_name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool type_nameSpecified
    {
      get { return this._type_name != null; }
      set { if (value == (this._type_name== null)) this._type_name = value ? this.type_name : (string)null; }
    }
    private bool ShouldSerializetype_name() { return type_nameSpecified; }
    private void Resettype_name() { type_nameSpecified = false; }
    
    private string _extendee;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"extendee", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string extendee
    {
      get { return _extendee?? ""; }
      set { _extendee = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool extendeeSpecified
    {
      get { return this._extendee != null; }
      set { if (value == (this._extendee== null)) this._extendee = value ? this.extendee : (string)null; }
    }
    private bool ShouldSerializeextendee() { return extendeeSpecified; }
    private void Resetextendee() { extendeeSpecified = false; }
    
    private string _default_value;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"default_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string default_value
    {
      get { return _default_value?? ""; }
      set { _default_value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool default_valueSpecified
    {
      get { return this._default_value != null; }
      set { if (value == (this._default_value== null)) this._default_value = value ? this.default_value : (string)null; }
    }
    private bool ShouldSerializedefault_value() { return default_valueSpecified; }
    private void Resetdefault_value() { default_valueSpecified = false; }
    
    private int? _oneof_index;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"oneof_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int oneof_index
    {
      get { return _oneof_index?? default(int); }
      set { _oneof_index = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool oneof_indexSpecified
    {
      get { return this._oneof_index != null; }
      set { if (value == (this._oneof_index== null)) this._oneof_index = value ? this.oneof_index : (int?)null; }
    }
    private bool ShouldSerializeoneof_index() { return oneof_indexSpecified; }
    private void Resetoneof_index() { oneof_indexSpecified = false; }
    
    private google.protobuf.FieldOptions _options = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"options", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public google.protobuf.FieldOptions options
    {
      get { return _options; }
      set { _options = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_DOUBLE", Value=1)]
      TYPE_DOUBLE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_FLOAT", Value=2)]
      TYPE_FLOAT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_INT64", Value=3)]
      TYPE_INT64 = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_UINT64", Value=4)]
      TYPE_UINT64 = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_INT32", Value=5)]
      TYPE_INT32 = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_FIXED64", Value=6)]
      TYPE_FIXED64 = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_FIXED32", Value=7)]
      TYPE_FIXED32 = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_BOOL", Value=8)]
      TYPE_BOOL = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_STRING", Value=9)]
      TYPE_STRING = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_GROUP", Value=10)]
      TYPE_GROUP = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_MESSAGE", Value=11)]
      TYPE_MESSAGE = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_BYTES", Value=12)]
      TYPE_BYTES = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_UINT32", Value=13)]
      TYPE_UINT32 = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_ENUM", Value=14)]
      TYPE_ENUM = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_SFIXED32", Value=15)]
      TYPE_SFIXED32 = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_SFIXED64", Value=16)]
      TYPE_SFIXED64 = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_SINT32", Value=17)]
      TYPE_SINT32 = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPE_SINT64", Value=18)]
      TYPE_SINT64 = 18
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Label")]
    public enum Label
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LABEL_OPTIONAL", Value=1)]
      LABEL_OPTIONAL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LABEL_REQUIRED", Value=2)]
      LABEL_REQUIRED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LABEL_REPEATED", Value=3)]
      LABEL_REPEATED = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OneofDescriptorProto")]
  public partial class OneofDescriptorProto : global::ProtoBuf.IExtensible
  {
    public OneofDescriptorProto() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name?? ""; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return this._name != null; }
      set { if (value == (this._name== null)) this._name = value ? this.name : (string)null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnumDescriptorProto")]
  public partial class EnumDescriptorProto : global::ProtoBuf.IExtensible
  {
    public EnumDescriptorProto() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name?? ""; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return this._name != null; }
      set { if (value == (this._name== null)) this._name = value ? this.name : (string)null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<google.protobuf.EnumValueDescriptorProto> _value = new global::System.Collections.Generic.List<google.protobuf.EnumValueDescriptorProto>();
    [global::ProtoBuf.ProtoMember(2, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<google.protobuf.EnumValueDescriptorProto> value
    {
      get { return _value; }
    }
  
    private google.protobuf.EnumOptions _options = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"options", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public google.protobuf.EnumOptions options
    {
      get { return _options; }
      set { _options = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnumValueDescriptorProto")]
  public partial class EnumValueDescriptorProto : global::ProtoBuf.IExtensible
  {
    public EnumValueDescriptorProto() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name?? ""; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return this._name != null; }
      set { if (value == (this._name== null)) this._name = value ? this.name : (string)null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    
    private int? _number;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int number
    {
      get { return _number?? default(int); }
      set { _number = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool numberSpecified
    {
      get { return this._number != null; }
      set { if (value == (this._number== null)) this._number = value ? this.number : (int?)null; }
    }
    private bool ShouldSerializenumber() { return numberSpecified; }
    private void Resetnumber() { numberSpecified = false; }
    
    private google.protobuf.EnumValueOptions _options = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"options", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public google.protobuf.EnumValueOptions options
    {
      get { return _options; }
      set { _options = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServiceDescriptorProto")]
  public partial class ServiceDescriptorProto : global::ProtoBuf.IExtensible
  {
    public ServiceDescriptorProto() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name?? ""; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return this._name != null; }
      set { if (value == (this._name== null)) this._name = value ? this.name : (string)null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<google.protobuf.MethodDescriptorProto> _method = new global::System.Collections.Generic.List<google.protobuf.MethodDescriptorProto>();
    [global::ProtoBuf.ProtoMember(2, Name=@"method", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<google.protobuf.MethodDescriptorProto> method
    {
      get { return _method; }
    }
  
    private google.protobuf.ServiceOptions _options = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"options", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public google.protobuf.ServiceOptions options
    {
      get { return _options; }
      set { _options = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MethodDescriptorProto")]
  public partial class MethodDescriptorProto : global::ProtoBuf.IExtensible
  {
    public MethodDescriptorProto() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name?? ""; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return this._name != null; }
      set { if (value == (this._name== null)) this._name = value ? this.name : (string)null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    
    private string _input_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"input_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string input_type
    {
      get { return _input_type?? ""; }
      set { _input_type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool input_typeSpecified
    {
      get { return this._input_type != null; }
      set { if (value == (this._input_type== null)) this._input_type = value ? this.input_type : (string)null; }
    }
    private bool ShouldSerializeinput_type() { return input_typeSpecified; }
    private void Resetinput_type() { input_typeSpecified = false; }
    
    private string _output_type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"output_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string output_type
    {
      get { return _output_type?? ""; }
      set { _output_type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool output_typeSpecified
    {
      get { return this._output_type != null; }
      set { if (value == (this._output_type== null)) this._output_type = value ? this.output_type : (string)null; }
    }
    private bool ShouldSerializeoutput_type() { return output_typeSpecified; }
    private void Resetoutput_type() { output_typeSpecified = false; }
    
    private google.protobuf.MethodOptions _options = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"options", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public google.protobuf.MethodOptions options
    {
      get { return _options; }
      set { _options = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FileOptions")]
  public partial class FileOptions : global::ProtoBuf.IExtensible
  {
    public FileOptions() {}
    
    private string _java_package;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"java_package", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string java_package
    {
      get { return _java_package?? ""; }
      set { _java_package = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool java_packageSpecified
    {
      get { return this._java_package != null; }
      set { if (value == (this._java_package== null)) this._java_package = value ? this.java_package : (string)null; }
    }
    private bool ShouldSerializejava_package() { return java_packageSpecified; }
    private void Resetjava_package() { java_packageSpecified = false; }
    
    private string _java_outer_classname;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"java_outer_classname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string java_outer_classname
    {
      get { return _java_outer_classname?? ""; }
      set { _java_outer_classname = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool java_outer_classnameSpecified
    {
      get { return this._java_outer_classname != null; }
      set { if (value == (this._java_outer_classname== null)) this._java_outer_classname = value ? this.java_outer_classname : (string)null; }
    }
    private bool ShouldSerializejava_outer_classname() { return java_outer_classnameSpecified; }
    private void Resetjava_outer_classname() { java_outer_classnameSpecified = false; }
    
    private bool? _java_multiple_files;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"java_multiple_files", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool java_multiple_files
    {
      get { return _java_multiple_files?? (bool)false; }
      set { _java_multiple_files = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool java_multiple_filesSpecified
    {
      get { return this._java_multiple_files != null; }
      set { if (value == (this._java_multiple_files== null)) this._java_multiple_files = value ? this.java_multiple_files : (bool?)null; }
    }
    private bool ShouldSerializejava_multiple_files() { return java_multiple_filesSpecified; }
    private void Resetjava_multiple_files() { java_multiple_filesSpecified = false; }
    
    private bool? _java_generate_equals_and_hash;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"java_generate_equals_and_hash", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool java_generate_equals_and_hash
    {
      get { return _java_generate_equals_and_hash?? (bool)false; }
      set { _java_generate_equals_and_hash = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool java_generate_equals_and_hashSpecified
    {
      get { return this._java_generate_equals_and_hash != null; }
      set { if (value == (this._java_generate_equals_and_hash== null)) this._java_generate_equals_and_hash = value ? this.java_generate_equals_and_hash : (bool?)null; }
    }
    private bool ShouldSerializejava_generate_equals_and_hash() { return java_generate_equals_and_hashSpecified; }
    private void Resetjava_generate_equals_and_hash() { java_generate_equals_and_hashSpecified = false; }
    
    private bool? _java_string_check_utf8;
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"java_string_check_utf8", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool java_string_check_utf8
    {
      get { return _java_string_check_utf8?? (bool)false; }
      set { _java_string_check_utf8 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool java_string_check_utf8Specified
    {
      get { return this._java_string_check_utf8 != null; }
      set { if (value == (this._java_string_check_utf8== null)) this._java_string_check_utf8 = value ? this.java_string_check_utf8 : (bool?)null; }
    }
    private bool ShouldSerializejava_string_check_utf8() { return java_string_check_utf8Specified; }
    private void Resetjava_string_check_utf8() { java_string_check_utf8Specified = false; }
    
    private google.protobuf.FileOptions.OptimizeMode? _optimize_for;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"optimize_for", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public google.protobuf.FileOptions.OptimizeMode optimize_for
    {
      get { return _optimize_for?? google.protobuf.FileOptions.OptimizeMode.SPEED; }
      set { _optimize_for = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool optimize_forSpecified
    {
      get { return this._optimize_for != null; }
      set { if (value == (this._optimize_for== null)) this._optimize_for = value ? this.optimize_for : (google.protobuf.FileOptions.OptimizeMode?)null; }
    }
    private bool ShouldSerializeoptimize_for() { return optimize_forSpecified; }
    private void Resetoptimize_for() { optimize_forSpecified = false; }
    
    private string _go_package;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"go_package", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string go_package
    {
      get { return _go_package?? ""; }
      set { _go_package = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool go_packageSpecified
    {
      get { return this._go_package != null; }
      set { if (value == (this._go_package== null)) this._go_package = value ? this.go_package : (string)null; }
    }
    private bool ShouldSerializego_package() { return go_packageSpecified; }
    private void Resetgo_package() { go_packageSpecified = false; }
    
    private bool? _cc_generic_services;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"cc_generic_services", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool cc_generic_services
    {
      get { return _cc_generic_services?? (bool)false; }
      set { _cc_generic_services = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool cc_generic_servicesSpecified
    {
      get { return this._cc_generic_services != null; }
      set { if (value == (this._cc_generic_services== null)) this._cc_generic_services = value ? this.cc_generic_services : (bool?)null; }
    }
    private bool ShouldSerializecc_generic_services() { return cc_generic_servicesSpecified; }
    private void Resetcc_generic_services() { cc_generic_servicesSpecified = false; }
    
    private bool? _java_generic_services;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"java_generic_services", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool java_generic_services
    {
      get { return _java_generic_services?? (bool)false; }
      set { _java_generic_services = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool java_generic_servicesSpecified
    {
      get { return this._java_generic_services != null; }
      set { if (value == (this._java_generic_services== null)) this._java_generic_services = value ? this.java_generic_services : (bool?)null; }
    }
    private bool ShouldSerializejava_generic_services() { return java_generic_servicesSpecified; }
    private void Resetjava_generic_services() { java_generic_servicesSpecified = false; }
    
    private bool? _py_generic_services;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"py_generic_services", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool py_generic_services
    {
      get { return _py_generic_services?? (bool)false; }
      set { _py_generic_services = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool py_generic_servicesSpecified
    {
      get { return this._py_generic_services != null; }
      set { if (value == (this._py_generic_services== null)) this._py_generic_services = value ? this.py_generic_services : (bool?)null; }
    }
    private bool ShouldSerializepy_generic_services() { return py_generic_servicesSpecified; }
    private void Resetpy_generic_services() { py_generic_servicesSpecified = false; }
    
    private bool? _deprecated;
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"deprecated", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool deprecated
    {
      get { return _deprecated?? (bool)false; }
      set { _deprecated = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool deprecatedSpecified
    {
      get { return this._deprecated != null; }
      set { if (value == (this._deprecated== null)) this._deprecated = value ? this.deprecated : (bool?)null; }
    }
    private bool ShouldSerializedeprecated() { return deprecatedSpecified; }
    private void Resetdeprecated() { deprecatedSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<google.protobuf.UninterpretedOption> _uninterpreted_option = new global::System.Collections.Generic.List<google.protobuf.UninterpretedOption>();
    [global::ProtoBuf.ProtoMember(999, Name=@"uninterpreted_option", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<google.protobuf.UninterpretedOption> uninterpreted_option
    {
      get { return _uninterpreted_option; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"OptimizeMode")]
    public enum OptimizeMode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SPEED", Value=1)]
      SPEED = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CODE_SIZE", Value=2)]
      CODE_SIZE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LITE_RUNTIME", Value=3)]
      LITE_RUNTIME = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageOptions")]
  public partial class MessageOptions : global::ProtoBuf.IExtensible
  {
    public MessageOptions() {}
    
    private bool? _message_set_wire_format;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_set_wire_format", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool message_set_wire_format
    {
      get { return _message_set_wire_format?? (bool)false; }
      set { _message_set_wire_format = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool message_set_wire_formatSpecified
    {
      get { return this._message_set_wire_format != null; }
      set { if (value == (this._message_set_wire_format== null)) this._message_set_wire_format = value ? this.message_set_wire_format : (bool?)null; }
    }
    private bool ShouldSerializemessage_set_wire_format() { return message_set_wire_formatSpecified; }
    private void Resetmessage_set_wire_format() { message_set_wire_formatSpecified = false; }
    
    private bool? _no_standard_descriptor_accessor;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"no_standard_descriptor_accessor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool no_standard_descriptor_accessor
    {
      get { return _no_standard_descriptor_accessor?? (bool)false; }
      set { _no_standard_descriptor_accessor = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool no_standard_descriptor_accessorSpecified
    {
      get { return this._no_standard_descriptor_accessor != null; }
      set { if (value == (this._no_standard_descriptor_accessor== null)) this._no_standard_descriptor_accessor = value ? this.no_standard_descriptor_accessor : (bool?)null; }
    }
    private bool ShouldSerializeno_standard_descriptor_accessor() { return no_standard_descriptor_accessorSpecified; }
    private void Resetno_standard_descriptor_accessor() { no_standard_descriptor_accessorSpecified = false; }
    
    private bool? _deprecated;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"deprecated", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool deprecated
    {
      get { return _deprecated?? (bool)false; }
      set { _deprecated = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool deprecatedSpecified
    {
      get { return this._deprecated != null; }
      set { if (value == (this._deprecated== null)) this._deprecated = value ? this.deprecated : (bool?)null; }
    }
    private bool ShouldSerializedeprecated() { return deprecatedSpecified; }
    private void Resetdeprecated() { deprecatedSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<google.protobuf.UninterpretedOption> _uninterpreted_option = new global::System.Collections.Generic.List<google.protobuf.UninterpretedOption>();
    [global::ProtoBuf.ProtoMember(999, Name=@"uninterpreted_option", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<google.protobuf.UninterpretedOption> uninterpreted_option
    {
      get { return _uninterpreted_option; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FieldOptions")]
  public partial class FieldOptions : global::ProtoBuf.IExtensible
  {
    public FieldOptions() {}
    
    private google.protobuf.FieldOptions.CType? _ctype;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ctype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public google.protobuf.FieldOptions.CType ctype
    {
      get { return _ctype?? google.protobuf.FieldOptions.CType.STRING; }
      set { _ctype = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ctypeSpecified
    {
      get { return this._ctype != null; }
      set { if (value == (this._ctype== null)) this._ctype = value ? this.ctype : (google.protobuf.FieldOptions.CType?)null; }
    }
    private bool ShouldSerializectype() { return ctypeSpecified; }
    private void Resetctype() { ctypeSpecified = false; }
    
    private bool? _packed;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"packed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool packed
    {
      get { return _packed?? default(bool); }
      set { _packed = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool packedSpecified
    {
      get { return this._packed != null; }
      set { if (value == (this._packed== null)) this._packed = value ? this.packed : (bool?)null; }
    }
    private bool ShouldSerializepacked() { return packedSpecified; }
    private void Resetpacked() { packedSpecified = false; }
    
    private bool? _lazy;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"lazy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool lazy
    {
      get { return _lazy?? (bool)false; }
      set { _lazy = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lazySpecified
    {
      get { return this._lazy != null; }
      set { if (value == (this._lazy== null)) this._lazy = value ? this.lazy : (bool?)null; }
    }
    private bool ShouldSerializelazy() { return lazySpecified; }
    private void Resetlazy() { lazySpecified = false; }
    
    private bool? _deprecated;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"deprecated", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool deprecated
    {
      get { return _deprecated?? (bool)false; }
      set { _deprecated = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool deprecatedSpecified
    {
      get { return this._deprecated != null; }
      set { if (value == (this._deprecated== null)) this._deprecated = value ? this.deprecated : (bool?)null; }
    }
    private bool ShouldSerializedeprecated() { return deprecatedSpecified; }
    private void Resetdeprecated() { deprecatedSpecified = false; }
    
    private string _experimental_map_key;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"experimental_map_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string experimental_map_key
    {
      get { return _experimental_map_key?? ""; }
      set { _experimental_map_key = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool experimental_map_keySpecified
    {
      get { return this._experimental_map_key != null; }
      set { if (value == (this._experimental_map_key== null)) this._experimental_map_key = value ? this.experimental_map_key : (string)null; }
    }
    private bool ShouldSerializeexperimental_map_key() { return experimental_map_keySpecified; }
    private void Resetexperimental_map_key() { experimental_map_keySpecified = false; }
    
    private bool? _weak;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"weak", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool weak
    {
      get { return _weak?? (bool)false; }
      set { _weak = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool weakSpecified
    {
      get { return this._weak != null; }
      set { if (value == (this._weak== null)) this._weak = value ? this.weak : (bool?)null; }
    }
    private bool ShouldSerializeweak() { return weakSpecified; }
    private void Resetweak() { weakSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<google.protobuf.UninterpretedOption> _uninterpreted_option = new global::System.Collections.Generic.List<google.protobuf.UninterpretedOption>();
    [global::ProtoBuf.ProtoMember(999, Name=@"uninterpreted_option", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<google.protobuf.UninterpretedOption> uninterpreted_option
    {
      get { return _uninterpreted_option; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CType")]
    public enum CType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"STRING", Value=0)]
      STRING = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CORD", Value=1)]
      CORD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STRING_PIECE", Value=2)]
      STRING_PIECE = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnumOptions")]
  public partial class EnumOptions : global::ProtoBuf.IExtensible
  {
    public EnumOptions() {}
    
    private bool? _allow_alias;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"allow_alias", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool allow_alias
    {
      get { return _allow_alias?? default(bool); }
      set { _allow_alias = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool allow_aliasSpecified
    {
      get { return this._allow_alias != null; }
      set { if (value == (this._allow_alias== null)) this._allow_alias = value ? this.allow_alias : (bool?)null; }
    }
    private bool ShouldSerializeallow_alias() { return allow_aliasSpecified; }
    private void Resetallow_alias() { allow_aliasSpecified = false; }
    
    private bool? _deprecated;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"deprecated", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool deprecated
    {
      get { return _deprecated?? (bool)false; }
      set { _deprecated = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool deprecatedSpecified
    {
      get { return this._deprecated != null; }
      set { if (value == (this._deprecated== null)) this._deprecated = value ? this.deprecated : (bool?)null; }
    }
    private bool ShouldSerializedeprecated() { return deprecatedSpecified; }
    private void Resetdeprecated() { deprecatedSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<google.protobuf.UninterpretedOption> _uninterpreted_option = new global::System.Collections.Generic.List<google.protobuf.UninterpretedOption>();
    [global::ProtoBuf.ProtoMember(999, Name=@"uninterpreted_option", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<google.protobuf.UninterpretedOption> uninterpreted_option
    {
      get { return _uninterpreted_option; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnumValueOptions")]
  public partial class EnumValueOptions : global::ProtoBuf.IExtensible
  {
    public EnumValueOptions() {}
    
    private bool? _deprecated;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"deprecated", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool deprecated
    {
      get { return _deprecated?? (bool)false; }
      set { _deprecated = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool deprecatedSpecified
    {
      get { return this._deprecated != null; }
      set { if (value == (this._deprecated== null)) this._deprecated = value ? this.deprecated : (bool?)null; }
    }
    private bool ShouldSerializedeprecated() { return deprecatedSpecified; }
    private void Resetdeprecated() { deprecatedSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<google.protobuf.UninterpretedOption> _uninterpreted_option = new global::System.Collections.Generic.List<google.protobuf.UninterpretedOption>();
    [global::ProtoBuf.ProtoMember(999, Name=@"uninterpreted_option", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<google.protobuf.UninterpretedOption> uninterpreted_option
    {
      get { return _uninterpreted_option; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServiceOptions")]
  public partial class ServiceOptions : global::ProtoBuf.IExtensible
  {
    public ServiceOptions() {}
    
    private bool? _deprecated;
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"deprecated", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool deprecated
    {
      get { return _deprecated?? (bool)false; }
      set { _deprecated = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool deprecatedSpecified
    {
      get { return this._deprecated != null; }
      set { if (value == (this._deprecated== null)) this._deprecated = value ? this.deprecated : (bool?)null; }
    }
    private bool ShouldSerializedeprecated() { return deprecatedSpecified; }
    private void Resetdeprecated() { deprecatedSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<google.protobuf.UninterpretedOption> _uninterpreted_option = new global::System.Collections.Generic.List<google.protobuf.UninterpretedOption>();
    [global::ProtoBuf.ProtoMember(999, Name=@"uninterpreted_option", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<google.protobuf.UninterpretedOption> uninterpreted_option
    {
      get { return _uninterpreted_option; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MethodOptions")]
  public partial class MethodOptions : global::ProtoBuf.IExtensible
  {
    public MethodOptions() {}
    
    private bool? _deprecated;
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"deprecated", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool deprecated
    {
      get { return _deprecated?? (bool)false; }
      set { _deprecated = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool deprecatedSpecified
    {
      get { return this._deprecated != null; }
      set { if (value == (this._deprecated== null)) this._deprecated = value ? this.deprecated : (bool?)null; }
    }
    private bool ShouldSerializedeprecated() { return deprecatedSpecified; }
    private void Resetdeprecated() { deprecatedSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<google.protobuf.UninterpretedOption> _uninterpreted_option = new global::System.Collections.Generic.List<google.protobuf.UninterpretedOption>();
    [global::ProtoBuf.ProtoMember(999, Name=@"uninterpreted_option", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<google.protobuf.UninterpretedOption> uninterpreted_option
    {
      get { return _uninterpreted_option; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UninterpretedOption")]
  public partial class UninterpretedOption : global::ProtoBuf.IExtensible
  {
    public UninterpretedOption() {}
    
    private readonly global::System.Collections.Generic.List<google.protobuf.UninterpretedOption.NamePart> _name = new global::System.Collections.Generic.List<google.protobuf.UninterpretedOption.NamePart>();
    [global::ProtoBuf.ProtoMember(2, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<google.protobuf.UninterpretedOption.NamePart> name
    {
      get { return _name; }
    }
  
    private string _identifier_value;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"identifier_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string identifier_value
    {
      get { return _identifier_value?? ""; }
      set { _identifier_value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool identifier_valueSpecified
    {
      get { return this._identifier_value != null; }
      set { if (value == (this._identifier_value== null)) this._identifier_value = value ? this.identifier_value : (string)null; }
    }
    private bool ShouldSerializeidentifier_value() { return identifier_valueSpecified; }
    private void Resetidentifier_value() { identifier_valueSpecified = false; }
    
    private ulong? _positive_int_value;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"positive_int_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong positive_int_value
    {
      get { return _positive_int_value?? default(ulong); }
      set { _positive_int_value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool positive_int_valueSpecified
    {
      get { return this._positive_int_value != null; }
      set { if (value == (this._positive_int_value== null)) this._positive_int_value = value ? this.positive_int_value : (ulong?)null; }
    }
    private bool ShouldSerializepositive_int_value() { return positive_int_valueSpecified; }
    private void Resetpositive_int_value() { positive_int_valueSpecified = false; }
    
    private long? _negative_int_value;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"negative_int_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long negative_int_value
    {
      get { return _negative_int_value?? default(long); }
      set { _negative_int_value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool negative_int_valueSpecified
    {
      get { return this._negative_int_value != null; }
      set { if (value == (this._negative_int_value== null)) this._negative_int_value = value ? this.negative_int_value : (long?)null; }
    }
    private bool ShouldSerializenegative_int_value() { return negative_int_valueSpecified; }
    private void Resetnegative_int_value() { negative_int_valueSpecified = false; }
    
    private double? _double_value;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"double_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double double_value
    {
      get { return _double_value?? default(double); }
      set { _double_value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool double_valueSpecified
    {
      get { return this._double_value != null; }
      set { if (value == (this._double_value== null)) this._double_value = value ? this.double_value : (double?)null; }
    }
    private bool ShouldSerializedouble_value() { return double_valueSpecified; }
    private void Resetdouble_value() { double_valueSpecified = false; }
    
    private byte[] _string_value;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"string_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] string_value
    {
      get { return _string_value?? null; }
      set { _string_value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool string_valueSpecified
    {
      get { return this._string_value != null; }
      set { if (value == (this._string_value== null)) this._string_value = value ? this.string_value : (byte[])null; }
    }
    private bool ShouldSerializestring_value() { return string_valueSpecified; }
    private void Resetstring_value() { string_valueSpecified = false; }
    
    private string _aggregate_value;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"aggregate_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string aggregate_value
    {
      get { return _aggregate_value?? ""; }
      set { _aggregate_value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool aggregate_valueSpecified
    {
      get { return this._aggregate_value != null; }
      set { if (value == (this._aggregate_value== null)) this._aggregate_value = value ? this.aggregate_value : (string)null; }
    }
    private bool ShouldSerializeaggregate_value() { return aggregate_valueSpecified; }
    private void Resetaggregate_value() { aggregate_valueSpecified = false; }
    
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NamePart")]
  public partial class NamePart : global::ProtoBuf.IExtensible
  {
    public NamePart() {}
    
    private string _name_part;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name_part", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name_part
    {
      get { return _name_part; }
      set { _name_part = value; }
    }
    private bool _is_extension;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"is_extension", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_extension
    {
      get { return _is_extension; }
      set { _is_extension = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SourceCodeInfo")]
  public partial class SourceCodeInfo : global::ProtoBuf.IExtensible
  {
    public SourceCodeInfo() {}
    
    private readonly global::System.Collections.Generic.List<google.protobuf.SourceCodeInfo.Location> _location = new global::System.Collections.Generic.List<google.protobuf.SourceCodeInfo.Location>();
    [global::ProtoBuf.ProtoMember(1, Name=@"location", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<google.protobuf.SourceCodeInfo.Location> location
    {
      get { return _location; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Location")]
  public partial class Location : global::ProtoBuf.IExtensible
  {
    public Location() {}
    
    private readonly global::System.Collections.Generic.List<int> _path = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"path", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<int> path
    {
      get { return _path; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _span = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"span", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<int> span
    {
      get { return _span; }
    }
  
    private string _leading_comments;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"leading_comments", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string leading_comments
    {
      get { return _leading_comments?? ""; }
      set { _leading_comments = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool leading_commentsSpecified
    {
      get { return this._leading_comments != null; }
      set { if (value == (this._leading_comments== null)) this._leading_comments = value ? this.leading_comments : (string)null; }
    }
    private bool ShouldSerializeleading_comments() { return leading_commentsSpecified; }
    private void Resetleading_comments() { leading_commentsSpecified = false; }
    
    private string _trailing_comments;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"trailing_comments", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string trailing_comments
    {
      get { return _trailing_comments?? ""; }
      set { _trailing_comments = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool trailing_commentsSpecified
    {
      get { return this._trailing_comments != null; }
      set { if (value == (this._trailing_comments== null)) this._trailing_comments = value ? this.trailing_comments : (string)null; }
    }
    private bool ShouldSerializetrailing_comments() { return trailing_commentsSpecified; }
    private void Resettrailing_comments() { trailing_commentsSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}