// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace google.protobuf {
	using System;


	[Serializable()]
	public class FileDescriptorSet {

		private Int32 _file_valueBehind;

		public virtual Int32 file {
			get {
				return _file_valueBehind;
			}
		}
	}

	[Serializable()]
	public class FileDescriptorProto {

		private Int32 _name_valueBehind;

		private Int32 _package_valueBehind;

		private Int32 _dependency_valueBehind;

		private Int32 _public_dependency_valueBehind;

		private Int32 _weak_dependency_valueBehind;

		private Int32 _message_type_valueBehind;

		private Int32 _enum_type_valueBehind;

		private Int32 _service_valueBehind;

		private Int32 _extension_valueBehind;

		private Int32 _options_valueBehind;

		private Int32 _source_code_info_valueBehind;

		public virtual Int32 name {
			get {
				return _name_valueBehind;
			}
		}

		public virtual Int32 package {
			get {
				return _package_valueBehind;
			}
		}

		public virtual Int32 dependency {
			get {
				return _dependency_valueBehind;
			}
		}

		public virtual Int32 public_dependency {
			get {
				return _public_dependency_valueBehind;
			}
		}

		public virtual Int32 weak_dependency {
			get {
				return _weak_dependency_valueBehind;
			}
		}

		public virtual Int32 message_type {
			get {
				return _message_type_valueBehind;
			}
		}

		public virtual Int32 enum_type {
			get {
				return _enum_type_valueBehind;
			}
		}

		public virtual Int32 service {
			get {
				return _service_valueBehind;
			}
		}

		public virtual Int32 extension {
			get {
				return _extension_valueBehind;
			}
		}

		public virtual Int32 options {
			get {
				return _options_valueBehind;
			}
		}

		public virtual Int32 source_code_info {
			get {
				return _source_code_info_valueBehind;
			}
		}
	}

	[Serializable()]
	public class DescriptorProto {

		private Int32 _name_valueBehind;

		private Int32 _field_valueBehind;

		private Int32 _extension_valueBehind;

		private Int32 _nested_type_valueBehind;

		private Int32 _enum_type_valueBehind;

		private Int32 _extension_range_valueBehind;

		private Int32 _oneof_decl_valueBehind;

		private Int32 _options_valueBehind;

		public virtual Int32 name {
			get {
				return _name_valueBehind;
			}
		}

		public virtual Int32 field {
			get {
				return _field_valueBehind;
			}
		}

		public virtual Int32 extension {
			get {
				return _extension_valueBehind;
			}
		}

		public virtual Int32 nested_type {
			get {
				return _nested_type_valueBehind;
			}
		}

		public virtual Int32 enum_type {
			get {
				return _enum_type_valueBehind;
			}
		}

		public virtual Int32 extension_range {
			get {
				return _extension_range_valueBehind;
			}
		}

		public virtual Int32 oneof_decl {
			get {
				return _oneof_decl_valueBehind;
			}
		}

		public virtual Int32 options {
			get {
				return _options_valueBehind;
			}
		}
	}

	[Serializable()]
	public class FieldDescriptorProto {

		private Int32 _name_valueBehind;

		private Int32 _number_valueBehind;

		private Int32 _label_valueBehind;

		private Int32 _type_valueBehind;

		private Int32 _type_name_valueBehind;

		private Int32 _extendee_valueBehind;

		private Int32 _default_value_valueBehind;

		private Int32 _oneof_index_valueBehind;

		private Int32 _options_valueBehind;

		public virtual Int32 name {
			get {
				return _name_valueBehind;
			}
		}

		public virtual Int32 number {
			get {
				return _number_valueBehind;
			}
		}

		public virtual Int32 label {
			get {
				return _label_valueBehind;
			}
		}

		public virtual Int32 type {
			get {
				return _type_valueBehind;
			}
		}

		public virtual Int32 type_name {
			get {
				return _type_name_valueBehind;
			}
		}

		public virtual Int32 extendee {
			get {
				return _extendee_valueBehind;
			}
		}

		public virtual Int32 default_value {
			get {
				return _default_value_valueBehind;
			}
		}

		public virtual Int32 oneof_index {
			get {
				return _oneof_index_valueBehind;
			}
		}

		public virtual Int32 options {
			get {
				return _options_valueBehind;
			}
		}

		public enum Type {

			TYPE_DOUBLE = 1,

			TYPE_FLOAT = 2,

			TYPE_INT64 = 3,

			TYPE_UINT64 = 4,

			TYPE_INT32 = 5,

			TYPE_FIXED64 = 6,

			TYPE_FIXED32 = 7,

			TYPE_BOOL = 8,

			TYPE_STRING = 9,

			TYPE_GROUP = 10,

			TYPE_MESSAGE = 11,

			TYPE_BYTES = 12,

			TYPE_UINT32 = 13,

			TYPE_ENUM = 14,

			TYPE_SFIXED32 = 15,

			TYPE_SFIXED64 = 16,

			TYPE_SINT32 = 17,

			TYPE_SINT64 = 18,
		}

		public enum Label {

			LABEL_OPTIONAL = 1,

			LABEL_REQUIRED = 2,

			LABEL_REPEATED = 3,
		}
	}

	[Serializable()]
	public class OneofDescriptorProto {

		private Int32 _name_valueBehind;

		public virtual Int32 name {
			get {
				return _name_valueBehind;
			}
		}
	}

	[Serializable()]
	public class EnumDescriptorProto {

		private Int32 _name_valueBehind;

		private Int32 _value_valueBehind;

		private Int32 _options_valueBehind;

		public virtual Int32 name {
			get {
				return _name_valueBehind;
			}
		}

		public virtual Int32 value {
			get {
				return _value_valueBehind;
			}
		}

		public virtual Int32 options {
			get {
				return _options_valueBehind;
			}
		}
	}

	[Serializable()]
	public class EnumValueDescriptorProto {

		private Int32 _name_valueBehind;

		private Int32 _number_valueBehind;

		private Int32 _options_valueBehind;

		public virtual Int32 name {
			get {
				return _name_valueBehind;
			}
		}

		public virtual Int32 number {
			get {
				return _number_valueBehind;
			}
		}

		public virtual Int32 options {
			get {
				return _options_valueBehind;
			}
		}
	}

	[Serializable()]
	public class ServiceDescriptorProto {

		private Int32 _name_valueBehind;

		private Int32 _method_valueBehind;

		private Int32 _options_valueBehind;

		public virtual Int32 name {
			get {
				return _name_valueBehind;
			}
		}

		public virtual Int32 method {
			get {
				return _method_valueBehind;
			}
		}

		public virtual Int32 options {
			get {
				return _options_valueBehind;
			}
		}
	}

	[Serializable()]
	public class MethodDescriptorProto {

		private Int32 _name_valueBehind;

		private Int32 _input_type_valueBehind;

		private Int32 _output_type_valueBehind;

		private Int32 _options_valueBehind;

		public virtual Int32 name {
			get {
				return _name_valueBehind;
			}
		}

		public virtual Int32 input_type {
			get {
				return _input_type_valueBehind;
			}
		}

		public virtual Int32 output_type {
			get {
				return _output_type_valueBehind;
			}
		}

		public virtual Int32 options {
			get {
				return _options_valueBehind;
			}
		}
	}

	[Serializable()]
	public class FileOptions {

		private Int32 _java_package_valueBehind;

		private Int32 _java_outer_classname_valueBehind;

		private Int32 _java_multiple_files_valueBehind;

		private Int32 _java_generate_equals_and_hash_valueBehind;

		private Int32 _java_string_check_utf8_valueBehind;

		private Int32 _optimize_for_valueBehind;

		private Int32 _go_package_valueBehind;

		private Int32 _cc_generic_services_valueBehind;

		private Int32 _java_generic_services_valueBehind;

		private Int32 _py_generic_services_valueBehind;

		private Int32 _deprecated_valueBehind;

		private Int32 _uninterpreted_option_valueBehind;

		public virtual Int32 java_package {
			get {
				return _java_package_valueBehind;
			}
		}

		public virtual Int32 java_outer_classname {
			get {
				return _java_outer_classname_valueBehind;
			}
		}

		public virtual Int32 java_multiple_files {
			get {
				return _java_multiple_files_valueBehind;
			}
		}

		public virtual Int32 java_generate_equals_and_hash {
			get {
				return _java_generate_equals_and_hash_valueBehind;
			}
		}

		public virtual Int32 java_string_check_utf8 {
			get {
				return _java_string_check_utf8_valueBehind;
			}
		}

		public virtual Int32 optimize_for {
			get {
				return _optimize_for_valueBehind;
			}
		}

		public virtual Int32 go_package {
			get {
				return _go_package_valueBehind;
			}
		}

		public virtual Int32 cc_generic_services {
			get {
				return _cc_generic_services_valueBehind;
			}
		}

		public virtual Int32 java_generic_services {
			get {
				return _java_generic_services_valueBehind;
			}
		}

		public virtual Int32 py_generic_services {
			get {
				return _py_generic_services_valueBehind;
			}
		}

		public virtual Int32 deprecated {
			get {
				return _deprecated_valueBehind;
			}
		}

		public virtual Int32 uninterpreted_option {
			get {
				return _uninterpreted_option_valueBehind;
			}
		}

		public enum OptimizeMode {

			SPEED = 1,

			CODE_SIZE = 2,

			LITE_RUNTIME = 3,
		}
	}

	[Serializable()]
	public class MessageOptions {

		private Int32 _message_set_wire_format_valueBehind;

		private Int32 _no_standard_descriptor_accessor_valueBehind;

		private Int32 _deprecated_valueBehind;

		private Int32 _uninterpreted_option_valueBehind;

		public virtual Int32 message_set_wire_format {
			get {
				return _message_set_wire_format_valueBehind;
			}
		}

		public virtual Int32 no_standard_descriptor_accessor {
			get {
				return _no_standard_descriptor_accessor_valueBehind;
			}
		}

		public virtual Int32 deprecated {
			get {
				return _deprecated_valueBehind;
			}
		}

		public virtual Int32 uninterpreted_option {
			get {
				return _uninterpreted_option_valueBehind;
			}
		}
	}

	[Serializable()]
	public class FieldOptions {

		private Int32 _ctype_valueBehind;

		private Int32 _packed_valueBehind;

		private Int32 _lazy_valueBehind;

		private Int32 _deprecated_valueBehind;

		private Int32 _experimental_map_key_valueBehind;

		private Int32 _weak_valueBehind;

		private Int32 _uninterpreted_option_valueBehind;

		public virtual Int32 ctype {
			get {
				return _ctype_valueBehind;
			}
		}

		public virtual Int32 packed {
			get {
				return _packed_valueBehind;
			}
		}

		public virtual Int32 lazy {
			get {
				return _lazy_valueBehind;
			}
		}

		public virtual Int32 deprecated {
			get {
				return _deprecated_valueBehind;
			}
		}

		public virtual Int32 experimental_map_key {
			get {
				return _experimental_map_key_valueBehind;
			}
		}

		public virtual Int32 weak {
			get {
				return _weak_valueBehind;
			}
		}

		public virtual Int32 uninterpreted_option {
			get {
				return _uninterpreted_option_valueBehind;
			}
		}

		public enum CType {

			STRING = 0,

			CORD = 1,

			STRING_PIECE = 2,
		}
	}

	[Serializable()]
	public class EnumOptions {

		private Int32 _allow_alias_valueBehind;

		private Int32 _deprecated_valueBehind;

		private Int32 _uninterpreted_option_valueBehind;

		public virtual Int32 allow_alias {
			get {
				return _allow_alias_valueBehind;
			}
		}

		public virtual Int32 deprecated {
			get {
				return _deprecated_valueBehind;
			}
		}

		public virtual Int32 uninterpreted_option {
			get {
				return _uninterpreted_option_valueBehind;
			}
		}
	}

	[Serializable()]
	public class EnumValueOptions {

		private Int32 _deprecated_valueBehind;

		private Int32 _uninterpreted_option_valueBehind;

		public virtual Int32 deprecated {
			get {
				return _deprecated_valueBehind;
			}
		}

		public virtual Int32 uninterpreted_option {
			get {
				return _uninterpreted_option_valueBehind;
			}
		}
	}

	[Serializable()]
	public class ServiceOptions {

		private Int32 _deprecated_valueBehind;

		private Int32 _uninterpreted_option_valueBehind;

		public virtual Int32 deprecated {
			get {
				return _deprecated_valueBehind;
			}
		}

		public virtual Int32 uninterpreted_option {
			get {
				return _uninterpreted_option_valueBehind;
			}
		}
	}

	[Serializable()]
	public class MethodOptions {

		private Int32 _deprecated_valueBehind;

		private Int32 _uninterpreted_option_valueBehind;

		public virtual Int32 deprecated {
			get {
				return _deprecated_valueBehind;
			}
		}

		public virtual Int32 uninterpreted_option {
			get {
				return _uninterpreted_option_valueBehind;
			}
		}
	}

	[Serializable()]
	public class UninterpretedOption {

		private Int32 _name_valueBehind;

		private Int32 _identifier_value_valueBehind;

		private Int32 _positive_int_value_valueBehind;

		private Int32 _negative_int_value_valueBehind;

		private Int32 _double_value_valueBehind;

		private Int32 _string_value_valueBehind;

		private Int32 _aggregate_value_valueBehind;

		public virtual Int32 name {
			get {
				return _name_valueBehind;
			}
		}

		public virtual Int32 identifier_value {
			get {
				return _identifier_value_valueBehind;
			}
		}

		public virtual Int32 positive_int_value {
			get {
				return _positive_int_value_valueBehind;
			}
		}

		public virtual Int32 negative_int_value {
			get {
				return _negative_int_value_valueBehind;
			}
		}

		public virtual Int32 double_value {
			get {
				return _double_value_valueBehind;
			}
		}

		public virtual Int32 string_value {
			get {
				return _string_value_valueBehind;
			}
		}

		public virtual Int32 aggregate_value {
			get {
				return _aggregate_value_valueBehind;
			}
		}
	}

	[Serializable()]
	public class SourceCodeInfo {

		private Int32 _location_valueBehind;

		public virtual Int32 location {
			get {
				return _location_valueBehind;
			}
		}
	}
}
